### ISSUE TITLE
Wrong installation

### ISSUE THREAD

**Issue by NormanBB** [KuoE0/oh-my-zsh-solarized-powerline-theme#3]
hi , i want to use this theme.But it seems that my config does not work. I am using termux, an app which can run linux on android.I installed Powerline fonts ,following the steps on that page.And here is the final result.I have no idea about it.Please help me.
![1](https://user-images.githubusercontent.com/18748504/42764369-070eadea-8948-11e8-814b-fca418a5782f.JPG)
![2](https://user-images.githubusercontent.com/18748504/42764411-1f9d26fc-8948-11e8-9072-89b24fe79e08.JPG)

**Comment by kuoe0** [comment]
Hi, I think that may be caused by termux. It maybe doesn't support some characters and colors.

**Comment by NormanBB** [comment]
I may found the answers.windows fonts may lead to the problem.But anyway, thank you for your theme.It is great !
